version: "3.8"

services:
  frozen-layer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frozen-layer-app
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - HOST=0.0.0.0
      - CRYSTAL_ENV=production
      - CONFIG_PATH=/app/config.json
    volumes:
      - ./config.docker.json:/app/config.json
    depends_on:
      - redis
    networks:
      - frozen-layer-network
    restart: unless-stopped

  redis:
    image: bitnami/redis:latest
    container_name: frozen-layer-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - frozen-layer-network
    restart: unless-stopped

networks:
  frozen-layer-network:
    driver: bridge
