name: "frozen-layer"
services:
  redis:
    image: "bitnami/redis:latest"
    env_file:
      - "${ENV_FILE}"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${STORE_PORT}:6379"
    volumes:
      - redis:/bitnami/redis/data

volumes:
  redis:
    driver: local
