#!/bin/bash

install_watchexec() {
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if command -v apt-get &> /dev/null; then
      sudo apt-get update && sudo apt-get install -y watchexec
    elif command -v yum &> /dev/null; then
      sudo yum install -y watchexec
    elif command -v dnf &> /dev/null; then
      sudo dnf install -y watchexec
    else
      echo "Unsupported Linux distribution. Please install 'watchexec' manually."
      exit 1
    fi
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    if command -v brew &> /dev/null; then
      brew install watchexec
    else
      echo "Homebrew is not installed. Please install 'watchexec' manually."
      exit 1
    fi
  else
    echo "Unsupported OS. Please install 'watchexec' manually."
    exit 1
  fi
}

if ! command -v watchexec &> /dev/null; then
  echo "'watchexec' is not installed. Installing..."
  install_watchexec
fi

# Execute the command
watchexec -r -w src -- crystal run src/frozen_layer.cr
# watchexec -r -w src -- crystal run --error-trace src/frozen_layer.cr


