name: Build Crystal

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev libreadline-dev

      - name: Setup Crystal
        uses: oprypin/install-crystal@v1

      - name: Build for ${{ matrix.platform }}
        run: |
          shards install
          crystal build src/frozen_layer.cr --release --target ${{ matrix.platform }}-unknown-linux-gnu

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: frzen-layer-${{ matrix.platform }}
          path: ./frozen_layer
